### ISSUE TITLE
Remove title attribute from example

### ISSUE THREAD

**Issue by LJWatson** [chaals/accesskey#1]
Suggest removing the title attributes from the first example in 5.5.2 (The accesskey attribute).

In this context the title attribute is more hinderance than help. It isn't well accessibility supported in general, isn't supported on touch devices at all, and can seriously inconvenience magnifier users. More info here:
http://www.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/

**Comment by chaals** [comment]
Agreed. Some of them were distinctly unhelpful, and none of them added anything obviously useful anyway.
Done: https://github.com/chaals/accesskey/commit/8fb5b498171a39509e5bbaedc556f7ecb1ff5951
